name: GOOLak
version: ${project.version}
main: net.akat.goolak.core.GOOLakPlugin
api-version: '1.16'
authors: [2FORWORD2]
softdepend: [ProtocolLib]
commands:
  goolak:
    description: GOOLak admin command
    usage: /<command> reload
    permission: goolak.admin
permissions:
  goolak.admin:
    default: op
